spring.application.name=talk_to_documents
server.address=0.0.0.0
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/talk_to_documents
spring.datasource.username=your_postgres_username
spring.datasource.password=your_postgres_password
spring.jpa.hibernate.ddl-auto=validate
spring.devtools.restart.enabled=true
sping.thymeleaf.cache=false
spring.web.resources.add-mappings=true
spring.mvc.throw-exception-if-no-handler-found=true